server:
  port: 81
  error:
    include-stacktrace: on_param

spring:
  database: h2
  console: true
  path: /h2

datasource:
  platform: h2
  url: jdbc:h2://localhost:81/h2
  username: joao
  password: joao
  driverClassName: org.h2.Driver